#!/usr/bin/env python

"""Tests for `asciju` package."""


import unittest

#from asciju import asciju
from asciju import convert_img_ascii


class TestAsciju(unittest.TestCase):
    """Tests for `asciju` package."""

    def setUp(self):
        """Set up test fixtures, if any."""

    def tearDown(self):
        """Tear down test fixtures, if any."""

    def test_convert_img_ascii(self):
        res1 = """BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBSSSBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB&%%**%$&#SBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBS$:..::::!**$#BBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBS#$!:::::!!!!!!*%$@&&#SBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBSS#%:::::::!!!!!!!!!**%$&SBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBS@:.:!**!!:!!!!!!!!*****%@SBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB%::!%@#SS#&%*!!!!!!!*****%&BBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBS&BB@!!*&&&&&#BS#$****%%%**!**%#BBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBS$*@B*::*@@&SS#BS$*!*%@SSS##@**%SBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBB#**%$:::::!*%$@$%!:!*$SBB#@@$$**#BBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBB&*%*!!::::!!*!:::::!*%@###&#@**%SBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBB&!!!*!:!!**%$*!*::!!!***%%%$$**@BBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBB%!**!!*%$$$**$&@%*%$***!!!!!!*SSSBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBSS%:!!%@@%**%$&#@$$%****!!!!$@$SBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB$!!!%@#&&&&&@&#@%**%*****%@%&BBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB&**********%$$&###&$%%**%$$#BBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB&$*****!**%$%**%@&&$***$$%#BBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB%%$$$$****%$%%****%%**@BSSBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBS**%&S##&@$$%%$%%%$%%$#BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBS&**%$&SBBBBSSSSS##&@@SBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBSSB@**%$$$#SBBBBBBBBBS@$SBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBS#SBB$**%$$$@&#####&&&&@$$SBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBS#SBBS$**%%$$$@&&@@@$$$@@$@SBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBSS#SBBBB@%%%%$$$$@@@$$$$$$$$#BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBSS#SBBBBS&$$$$$$$$$$$$$$$$$$@SBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBSSSBBBBBBS@$$$$$$$@@@$$$$$$@@#BBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBS$%%%$$$$$$$$$$$@@@&SBBBBBBSSBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBSS$%%**%%%$$$$%%$$$@#BBBBBBBSBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBS##@%****%%%%%%%%%%%@SSBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBS##&$%**%%%%%*%%%%%@#SBSBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBSS##@%**%%%%%***$&SSSSBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBSS@%**%%****$#SSSSBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBS&$%****$@#BBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBS@@@%$@&SBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB#$$###BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBSBBS&#SBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"""
        self.assertEqual(convert_img_ascii("tests/image/1.jpg","tests/output/test.txt"),res1)

    def test_convert_img_ascii_using_func(self):
        self.assertEqual(convert_img_ascii("tests/image/1.jpg","tests/output/test.txt"),convert_img_ascii("tests/image/1.jpg","tests/output/1.txt"))

if __name__ == '__main__':
    unittest.main() 

